#!perl

use Config;
open F, ">", "mitdk-renew.bat";
print F '@wperl ' . $Config{sitebin} . "/mitdk-renew-lease -la";
close F;

open F, ">", "mitdk-server.bat";
print F '@wperl ' . $Config{sitebin} . "/mitdk2pop -p 8111";
close F;
